import Skeleton from "@/components/Skeleton";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Menu from "@/components/Menu";

export const metadata = {
  title: "Economy Express",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-ubuntu">
        <div className="py-2">
          <Navbar />
          <Menu />
        </div>
        <Skeleton>{children}</Skeleton>
      </body>
    </html>
  );
}
